# -*- coding: utf-8 -*-
"""clipper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItBAArlmrrrfK5X-Br20hetSflDAhkX1
"""

#import pandas as pd

#getting book title
book_name = input("Enter the name of the book: ")
#opening my clippings
clippings = open("My Clippings.txt", encoding="utf8")
#split into lines
clip_lines = clippings.readlines()
#create list of lines that matter to us
#lines = pd.DataFrame(columns=['Line'])
lines = []
save = False
for line in clip_lines:
    if book_name in line:
        save = True
    if '==========' in line:
        save = False
    if save:
        lines.append(line)
    
i = 0
highlights = []
#from char 20 to get "page ###"

for line in lines:
    if i == 1:
        end_pos = line.find('|')
        page_tag = line[20:end_pos]
        page_tag += '\n'
        highlights.append(page_tag)
    
    if i == 3:
        highlights.append(line)
        i = 0
        continue
    i += 1

#close clippings
clippings.close()
#save to a file
filename = book_name + "_highlights.txt"
file = open(filename, 'w')
for clip in highlights:
  file.write(clip)
file.close()

highlights